version: '3'

services:
  pushgateway:
    image: prom/pushgateway
    command:
      - '--push.disable-consistency-check'
    ports:
      - 9091:9091
  prometheus:
    image: prom/prometheus
    ## open the ports to use directly without proxy
    ports:
      - 9090:9090
    #expose:
    #  - 9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: root # thanks red hat
    environment:
      GF_SECURITY_ADMIN_USER: exp
      GF_SECURITY_ADMIN_PASSWORD: exp
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      # clear the data folder out when resetting local environment
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboard:/prometheus-experiments/dashboards
